//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClubSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookMatchCard
    {
        public BookMatchCard()
        {
            this.MatchCardOrders = new HashSet<MatchCardOrder>();
        }
    
        public int BookId { get; set; }
        public int UserId { get; set; }
        public System.DateTime BookDate { get; set; }
        public double totalbill { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<MatchCardOrder> MatchCardOrders { get; set; }
    }
}
