//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClubSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cycle1
    {
        public int CycleId { get; set; }
        public string CycleName { get; set; }
        public string HomeTeam { get; set; }
        public string AwayTeam { get; set; }
        public string Studim { get; set; }
        public Nullable<System.DateTime> MatchTime { get; set; }
        public string CommenacatorSport { get; set; }
        public string cause { get; set; }
    }
}
