//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClubSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cycle
    {
        public Cycle()
        {
            this.CycleTables = new HashSet<CycleTable>();
        }
    
        public int Cycle_id { get; set; }
        public int Match_id { get; set; }
        public string Cycle_name { get; set; }
        public string CycleInformation { get; set; }
        public int Team_id { get; set; }
        public string TeamName { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Team Team { get; set; }
        public virtual ICollection<CycleTable> CycleTables { get; set; }
    }
}
