//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClubSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CycleTable
    {
        public int CycleTable_id { get; set; }
        public int Cycle_id { get; set; }
        public int Team_id { get; set; }
        public int SortTeam { get; set; }
        public int goals { get; set; }
        public int Assest { get; set; }
        public int YallowCard { get; set; }
        public int RedCard { get; set; }
        public int Differnce { get; set; }
    
        public virtual Cycle Cycle { get; set; }
        public virtual Team Team { get; set; }
    }
}
