//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClubSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.TeamMangments = new HashSet<TeamMangment>();
        }
    
        public int Employee_id { get; set; }
        public string EmployeeName { get; set; }
        public string Email { get; set; }
        public string Adress { get; set; }
    
        public virtual ICollection<TeamMangment> TeamMangments { get; set; }
    }
}
