//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClubSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fan
    {
        public int Fans_id { get; set; }
        public Nullable<int> Team_id { get; set; }
        public Nullable<int> number { get; set; }
        public string city { get; set; }
        public string country { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
