//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClubSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    
    {
        SportSiteEntities40 db = new SportSiteEntities40();
        public invoice()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int in_id { get; set; }
        public int in_user { get; set; }
        public System.DateTime invoiceDate { get; set; }
        public double TotalBill { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Order> Orders { get; set; }

        public void Add(invoice i)
        {
            db.invoices.Add(i);
        }

        public void SaveChanges()
        {
            db.SaveChanges();
        }

    }
}
