//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClubSite.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Market
    {
        public int MarketId { get; set; }
        public int TeamId { get; set; }
        public string TeamSell { get; set; }
        public string Teambay { get; set; }
        public string PlayerName { get; set; }
        public double Price { get; set; }
        public string Condation { get; set; }
        public string HomeTeamImage { get; set; }
        public string AwayTeamImage { get; set; }
        public virtual Team Team { get; set; }
    }
}
