//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClubSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.Linq;
    public partial class Match
    {
        TeamsRepository t = new TeamsRepository();
        public Match()
        {
            this.Cycles = new HashSet<Cycle>();
            this.MatchCards = new HashSet<MatchCard>();
            this.MatchReports = new HashSet<MatchReport>();
        }

        public int Match_id { get; set; }
        public Nullable<int> HomeTeam { get; set; }
        public Nullable<int> AwayTeam { get; set; }
        public Nullable<int> HomeGoals { get; set; }
        public Nullable<int> AwayGoals { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string HomeTeamImage { get; set; }
        public string AwayTeamImage { get; set; }

        public string stadium { get; set; }

        public virtual ICollection<Cycle> Cycles { get; set; }
        public virtual ICollection<MatchCard> MatchCards { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual ICollection<MatchReport> MatchReports { get; set; }
        public string HomeTeamName
        {
            get
            {
                return t.GetAllTeams().Where(k => k.Team_id == this.HomeTeam).FirstOrDefault().TeamName;
            }
        }
        public string AwayTeamName
        {
            get
            {
                return t.GetAllTeams().Where(k => k.Team_id == this.AwayTeam).FirstOrDefault().TeamName;
            }
        }
    }
}

