//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClubSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchCard
    {
        public MatchCard()
        {
            this.MatchCardOrders = new HashSet<MatchCardOrder>();
        }
    
        public int MatchCard_id { get; set; }
        public int Match_id { get; set; }
        public string HomeTeam { get; set; }
        public string AwayTeam { get; set; }
        public string Studium { get; set; }
        public decimal Price { get; set; }
        public System.DateTime time { get; set; }
        public string ImagePath { get; set; }
        public int RankCard { get; set; }
        public string KindOfCard { get; set; }
        public int ChairNumber { get; set; }
        public Nullable<bool> IsLocked { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual ICollection<MatchCardOrder> MatchCardOrders { get; set; }
    }
}
