//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClubSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchCardOrder
    {
        public int MOId { get; set; }
        public int MatchCardId { get; set; }
        public int UserId { get; set; }
        public int BookMatchCardId { get; set; }
        public System.DateTime MatchOrderDate { get; set; }
        public double Bill { get; set; }
        public int UnitPrice { get; set; }
    
        public virtual BookMatchCard BookMatchCard { get; set; }
        public virtual MatchCard MatchCard { get; set; }
        public virtual User User { get; set; }
    }
}
