//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClubSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportSiteEntities40 : DbContext
    {
        public SportSiteEntities40()
            : base("name=SportSiteEntities40")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookMatchCard> BookMatchCards { get; set; }
        public virtual DbSet<Cycle> Cycles { get; set; }
        public virtual DbSet<Cycle1> Cycle1 { get; set; }
        public virtual DbSet<CycleTable> CycleTables { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Fan> Fans { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<Market> Markets { get; set; }
        public virtual DbSet<MatchCard> MatchCards { get; set; }
        public virtual DbSet<MatchCardOrder> MatchCardOrders { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<MatchReport> MatchReports { get; set; }
        public virtual DbSet<Name> Names { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlayerMarketMove> PlayerMarketMoves { get; set; }
        public virtual DbSet<PredictMatchScore> PredictMatchScores { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Roule> Roules { get; set; }
        public virtual DbSet<Studium> Studiums { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<TeamMangment> TeamMangments { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
