//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClubSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        SportSiteEntities40 db = new SportSiteEntities40();
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public int UserId { get; set; }
        public int in_id { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int quantity { get; set; }
        public double bill { get; set; }
        public int UnitPrice { get; set; }
    
        public virtual invoice invoice { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public void Add(Order o)
        {
            db.Orders.Add(o);
        }

        public void SaveChanges()
        {
            db.SaveChanges();
        }

    }
}
