//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClubSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerMarketMove
    {
        public int MarketMoveId { get; set; }
        public string playername { get; set; }
        public string oldTeam { get; set; }
        public string NewTeam { get; set; }
        public Nullable<double> Price { get; set; }
        public string condation { get; set; }
        public Nullable<double> salary { get; set; }
        public string Awards { get; set; }
    }
}
