//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClubSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int Player_id { get; set; }
        public Nullable<int> Team_id { get; set; }
        public string TeamName { get; set; }
        public string PlayerName { get; set; }
        public Nullable<double> Long { get; set; }
        public Nullable<double> Wieght { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
