//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClubSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PredictMatchScore
    {
        public int predict_id { get; set; }
        public string HomeTeam { get; set; }
        public string AwayTeam { get; set; }
        public string Studium { get; set; }
        public string MatchTime { get; set; }
        public string Weather { get; set; }
        public Nullable<int> TotalPointHomeTeam { get; set; }
        public Nullable<int> TotalPointAwayTeam { get; set; }
        public Nullable<int> RankHomeTeam { get; set; }
        public Nullable<int> RankAwayTeam { get; set; }
        public string TeamWon { get; set; }
        public Nullable<int> FTHG { get; set; }
        public Nullable<int> FTAG { get; set; }
        public Nullable<int> HST { get; set; }
        public Nullable<int> AST { get; set; }
        public Nullable<double> HTGDIFF { get; set; }
        public Nullable<double> ATGDIFF { get; set; }
        public string powerofPlayer { get; set; }
    }
}
