//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClubSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMangment
    {
        public int TeamMangment_id { get; set; }
        public Nullable<int> Team_id { get; set; }
        public string Owner { get; set; }
        public string Coatch { get; set; }
        public Nullable<int> Employee_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Team Team { get; set; }
    }
}
