//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClubSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Cycles = new HashSet<Cycle>();
            this.CycleTables = new HashSet<CycleTable>();
            this.Fans = new HashSet<Fan>();
            this.Markets = new HashSet<Market>();
            this.Matches = new HashSet<Match>();
            this.Matches1 = new HashSet<Match>();
            this.Players = new HashSet<Player>();
            this.Studiums = new HashSet<Studium>();
            this.TeamMangments = new HashSet<TeamMangment>();
        }
    
        public int Team_id { get; set; }
        public string TeamName { get; set; }
        public string HomeTeamImage { get; set; }
        public string AwayTeamImage { get; set; }

        public string stadium { get; set; }
        public virtual ICollection<Cycle> Cycles { get; set; }
        public virtual ICollection<CycleTable> CycleTables { get; set; }
        public virtual ICollection<Fan> Fans { get; set; }
        public virtual ICollection<Market> Markets { get; set; }
        public virtual ICollection<Match> Matches { get; set; }
        public virtual ICollection<Match> Matches1 { get; set; }
        public virtual ICollection<Player> Players { get; set; }
        public virtual ICollection<Studium> Studiums { get; set; }
        public virtual ICollection<TeamMangment> TeamMangments { get; set; }
    }
}
